baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Gamefficacy - efficient gaming'
enableEmoji = true


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 4

